### ISSUE TITLE
Headless Button

### ISSUE THREAD

**Issue by guangliang2019** [guangliang2019/Prototype-UI#3]
Button

Typically, this will be the first component in a component library :)

**Comment by cyjin-yl** [comment]
## Agent evidence · Headless Button 的当前实现示例

### 请求转述与历史边界

Agent 根据原 Issue 脱敏转述：为组件库提供一个 Headless Button。原始外部 prompt 不可得；本条只有简短需求，2024年已关闭，没有逐项验收记录。当前用户要求 Agent 为包括 closed 在内的所有历史 Issue 补充对应题材的图，不要求人类补材料。

下面是**2026-09-15当前源码的真实示例**，不是2024年实现的重现，也不是补写当年的验收结论。原文、作者与关闭状态保留。

### Headless 的是视觉决策，不是交互行为

官方 Base Button 页面实际运行两个 `wc-base-button`：左边可激活，右边 disabled。边框、padding与半透明由[示例的消费层 className](https://github.com/Proto-UI/Proto-UI/blob/4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae/apps/www/src/content/docs/zh-cn/demo-base-button.demo.ts)提供，不是 Base 内置的视觉 variant。

![当前官方WC Base Button示例：可激活的Run action与disabled对照，未改产品DOM或CSS](https://raw.githubusercontent.com/Proto-UI/Proto-UI/b7c4fc4b6920837b4f95062ad07b05aeb3fc3e40/evidence/2026-09-15/redo/3-current-initial-5c7b44ed4fde.png)

在前方的 Adapter selector 定位焦点，再用真实 Tab 进入 Run action，**左侧出现可见焦点轮廓**；实测 exposed `focused=true`、`focusVisible=true`。下图展示真实组件的这个状态，不是把断言写到图片里。

![真实Tab进入Run action后出现焦点轮廓，disabled对照保持禁用](https://raw.githubusercontent.com/Proto-UI/Proto-UI/b7c4fc4b6920837b4f95062ad07b05aeb3fc3e40/evidence/2026-09-15/redo/3-current-keyboard-focus-e17db27a72a0.png)

鼠标按下/松开时，实测 `pressed` 为false→true→false。一次鼠标激活、一次Space、一次Enter分别产生一个 outward custom `click`，累计3个；再向disabled示例发送真实鼠标按下/松开，它保持unpressed，custom click总数仍为3。浏览器原生click另行记录，不与Proto业务CustomEvent重复计数。截图说明组件外观与焦点，事件行为由原始轨迹支持，不能仅凭画面推出事件数。

### 当前事实从哪里来

- [P-BASE-BUTTON](https://github.com/Proto-UI/Proto-UI/blob/4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae/spec/prototypes/P-BASE-BUTTON.yaml) 与 [T-BASE-BUTTON-0001](https://github.com/Proto-UI/Proto-UI/blob/4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae/spec/tests/T-BASE-BUTTON-0001.yaml) 当前都是 **draft**，描述上述command、disabled、focus与activation方向，不升级成稳定保证。
- [button.proto.ts](https://github.com/Proto-UI/Proto-UI/blob/4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae/packages/prototypes/base/src/button/button.proto.ts) 负责官方trigger入口、瞬态状态、disabled门控和click输出；本轮未改它。
- `asButton` 是同一Button协议的authoring entry，不能据此把其他Base协议都改为继承Button。[当前编目方向](https://github.com/Proto-UI/Proto-UI/blob/4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae/spec/decisions/D-BASE-PROTOTYPE-INDEPENDENCE-0001.yaml)优先于仍称其为通用substrate的旧 `button.v0.md`；这个文字差异没有被偷偷解释成新的设计许可。

[固定版本复现说明、只读事件采样方法与JSON轨迹](https://gist.github.com/cyjin-yl/a716d0491c9b49a3896baa7135507df0/4b6950451082aafe70902350c37a65594549d6ef)。源码基线 `4d28834624dfcd1a0fd31aa6ec0d5f6e30482aae`，Windows/Node22.22.1/pnpm10.32.1/HeadlessChrome152，1440×1000 light，Astro dev `/zh-cn/ui-libraries/base/button/`。复用官方页面，不造模拟产品；Gist提供说明和数据，实际demo源码在上面的仓库链接。两张PNG逐张目视、上传并以匿名下载哈希核验。

当前WC基本交互示例的补图范围已完成。完整历史验收仍为 **partial**：未重建2024实现、未覆盖React/Vue、其他浏览器、dark/mobile、remount及所有Button语义；本例也不否定另行报告的 #650。Agent后续按题材继续补证，不重新开启/关闭Issue，不声称修复或人工批准。MIT仓库来源，AI辅助取证与说明。
